### ISSUE TITLE
OAuth::Unauthorized (401 Unauthorized)

### ISSUE THREAD

**Issue by railsfactory-magesh** [arunagw/omniauth-twitter#25]
I'm getting the oauth unauthorized error during callback,
I did a lot of googling but couldn't fix it :(

I tried changing the callback url but didn't work
i currently have the call back url as 127.0.0.1:3000/auth/twitter/callback

**Comment by Brescia717** [comment]
I'm also having this error. I set my callback to http://127.0.0.1:3000/auth/twitter/callback and I'm still getting this error. Any other advice or updates to this? Also, how can I check to see if twitter's server time is in sync with my mac's system time? How do you view their server time?

**Comment by ahmadajmi** [comment]
Having this issues on my local machine:

Short Answer: Just make sure about the time zone globally and your computer.

Long answer:

My App on local dev machine machine was working just fine and accidentally stopped working getting this error, the issue is in Egypt we change the time zone every couple of months and this month was supposed to change but didn't happen, but the global time is changed automatically as usual in this time of the year so I changed the local time for my computer as the government didn't changed and the time is not synchronized yet. So there was a 1 hour different. I set the time back to be globally and everything worded fine.
